### PR TITLE
Don't allow free hosts. (Specifically glitch.com)

### PR DESCRIPTION
**Pull request by anishanne**
Considering the recent string of downtime with glitch.com (along with the fact that projects get rate-limited after 4k requests making it easy for anyone to bring a bot list down), I think we should not allow free website hosting.

Glitch is, however, releasing a paid plan, which is why it says "not be hosted on a free host", if your paying for the glitch, then it isn't a free host making it ok.

### CODE REVIEW

**Comment by advaith1** [comment]
rule 4 already requires good uptime, and users could just use Cloudflare to block attacks, so I disagree with this.

**Comment by anishanne** [comment]
> rule 4 already requires good uptime, and users could just use Cloudflare to block attacks, so I disagree with this.

Right but there's no clear set number on that. And botblock doesn't track uptime, its just a general rule. If this isn't the way to do it, then a number has to be set, something like 90% uptime required

**Comment by Andre601** [comment]
> if your paying for the glich

Boy, that can sound wrong xD

**Comment by carolinaisslaying** [comment]
This was already proposed in #11 and was declined:

IPv4's exact quotes:
> I don’t mind glitch if you’re using a custom domain, it’s always up and otherwise functioning fine.

> With that in mind, you wouldn't actually be able to tell it was on glitch over any other hosting service, so I don't see why we should block it. Quite a few existing and working bot lists are hosted on glitch as far as I know.

**Comment by MattIPv4** [comment]
Thanks folks 👍

**Comment by qtAmyVT** [comment]
We need to say that this is a **free hosting**, what did you expect? Like, hosting a bot list on a free hosting by you didn't have money for **buying VPS**, but you know you can call this as the "money saver". And i know glitch is having a hard downtimes, but i still use glitch for testing purposes.

**Pull request closed without merging**
