### PR TITLE
Update things (see comment)

### PR DESCRIPTION
**Pull request by davidcralph**
* Build upon not allowing "[xyz].glitch.me" by not allowing any free subdomains (such as us.to)
* Make punctuation consistent

### CODE REVIEW

**Comment by advaith1** [comment]
That list would get pretty long, maybe just shorten it to you have to pay for your domain and include glitch as an example because it's the most common

**Review by MattIPv4 — COMMENTED** [review]
I don't see the point in this - the first point is regarding using a respectable domain, the second is specifically about the usage of Glitch. I don't see a reason to blur the difference between these points further?

**Comment by Andre601** [comment]
#6 already deals with the first point and is still open for improvements and changes.

**Comment by davidcralph** [comment]
Didn't notice #6, closing this PR now

**Pull request closed without merging**
